with-expecter: True
# outpkg: mocks
resolve-type-alias: false
disable-version-string: true
issue-845-fix: true
filename: "mock_{{.InterfaceName}}.go"
dir: "{{.InterfaceDir}}"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
inpackage: True
packages:
    github.com/lawrencegripper/actions-dns-monitoring/pkg/ebpf:
        config:
        interfaces:
            DnsFirewall:
              config: