
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Pre-build image and run make ci-build in dev container
      uses: devcontainers/ci@v0.3
      with:
        push: never
        runCmd: make ci
    
    # These tests can't be run in the devcontainer as rely on the host cgroup mapping for docker attach
    - name: Run host only smoketests
      run: make ./script/smoke-test-host.sh