
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Pre-build image and run make ci-build in dev container
      uses: devcontainers/ci@v0.3
      with:
        push: never
        runCmd: make ci
    
    - name: Install mkcert
      run: |
        sudo apt-get update
        sudo apt-get install -y libnss3-tools
        curl -JLO "https://github.com/FiloSottile/mkcert/releases/download/v1.4.4/mkcert-v1.4.4-linux-amd64"
        sudo chmod +x mkcert-v*-linux-amd64
        sudo mv mkcert-v*-linux-amd64 /usr/local/bin/mkcert
        mkcert -install

    # These tests can't be run in the devcontainer as rely on the host cgroup mapping for docker attach
    - name: Run host only smoketests
      run: ./script/smoke-test-host.sh