
name: Real world

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  real-world-no-firewall:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run `real-world.sh` without firewall
      run: ./script/real-world.sh

  real-world-with-firewall:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build
      run: |
        sudo ./script/linux-dependencies
        make build
    
    - name: Install mkcert
      run: |
        sudo apt-get update
        sudo apt-get install -y libnss3-tools
        curl -JLO "https://github.com/FiloSottile/mkcert/releases/download/v1.4.4/mkcert-v1.4.4-linux-amd64"
        sudo chmod +x mkcert-v*-linux-amd64
        sudo mv mkcert-v*-linux-amd64 /usr/local/bin/mkcert
        sudo mkcert -install

    - name: Run `real-world.sh` with firewall
      run: ./script/real-world.sh
      env:
        ATTACH: true

    - name: Firewall logs
      run: cat /tmp/ebpf-cgroup-firewall.log
      if: always()

