name: Soak Test

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight UTC
  workflow_dispatch: # Allow manual trigger
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  soak-test:
    runs-on: ubuntu-latest
    timeout-minutes: 35 # Container setup + 15min test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pre-build image and run soak test in dev container
        uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: make soaktest
